# python_exceptions
dealing with exceptions
